# Ruby solution to Euler's Problem 2:
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

sum_1 = 1
sum_2 = 2
even_sum_total = 0

while sum_2 <= 4000000
	if sum_2%2 == 0
		even_sum_total += sum_2
	end
	temp_sum_1 = sum_1
	sum_1 = sum_2
	sum_2 = temp_sum_1 + sum_2
end

puts even_sum_total


